name: mortalheart_mall
description: 凡人之心：凡心之所向，如履平地。
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  easy_refresh: ^3.3.2+1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - images/ic_home.png
     - images/ic_home_active.png
     - images/ic_category.png
     - images/ic_category_active.png
     - images/ic_cart.png
     - images/ic_cart_active.png
     - images/ic_mine.png
     - images/ic_mine_active.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
