name: mortalheart_mall
description: 凡人之心：凡心之所向，如履平地。
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  easy_refresh: ^3.3.2+1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_group_list_view: ^1.0.3


  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - images/ic_home.png
     - images/ic_home_active.png
     - images/ic_stoll.png
     - images/ic_stoll_active.png
     - images/ic_category.png
     - images/ic_category_active.png
     - images/ic_cart.png
     - images/ic_cart_active.png
     - images/ic_mine.png
     - images/ic_mine_active.png
     - images/default.png
     - images/classification.png
     - images/message.png
     - images/search.png
     - images/scan.png
     - images/camera.png
     - images/address.png
     - images/ellipsis.png
     - images/check.png
     - images/clone.png
     - images/probably_like.png
     - images/store.png
     - images/arrow_right.png
     - images/mine_top_bg.png
     - images/ic_friend.png
     - images/ic_setting.png
     - images/ic_message.png
     - images/goods_star.png
     - images/store_focus.png
     - images/look_history.png
     - images/todo_pay.png
     - images/todo_get.png
     - images/todo_evaluate.png
     - images/todo_exchange.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
